# [START app_yaml]
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7

resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10

threadsafe: true

# [START env_variables]
env_variables:
    NODE_ENV: production
    BASE_URL: 'https://iotcore-209004.appspot.com'
# [END env_variables]

# [END app_yaml]
