# [START app_yaml]
env: flex
runtime: nodejs

# [START env_variables]
env_variables:
    NODE_ENV: production
    BASE_URL: 'https://iotcore-209004.appspot.com'
# [END env_variables]

# [END app_yaml]
