# [START app_yaml]
runtime: nodejs
env: flex
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

threadsafe: true

# [START env_variables]
env_variables:
    NODE_ENV: production
    BASE_URL: 'https://iotcore-209004.appspot.com'
# [END env_variables]

# [END app_yaml]
