# [START app_yaml]
runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# [START env_variables]
env_variables:
    NODE_ENV: production
    BASE_URL: 'https://iotcore-209004.appspot.com'
# [END env_variables]

# [END app_yaml]
